name: Test Node.js App
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code - clone
        uses: actions/checkout@v2

      - name: Set up Node.js instruction
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: npm ci

      - name: Verify Run tests
        run: npm test

      - name: Test Build docker image final
        run: |
          docker build -t probandogithubactions .

      - name: Push Docker image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker tag probandogithubactions ${{ secrets.DOCKERHUB_USERNAME }}/probandogithubactions
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/probandogithubactions

